spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@webfluxcoursecluster.dgpbpte.mongodb.net/HENRIQUE_WEBFLUX?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux-course